using System;
using System.Runtime.Serialization;

namespace ProjectLibrary
{
    /// <summary>
    /// An interface of a flight. Represent a single flight, either landing or departure, generated by the simulator.
    /// </summary>
    public interface IFlight
    {
        /// <summary>
        /// Unique id of a flight
        /// </summary>
        string Id { get; set; }

        /// <summary>
        /// Discripe the type of the flight state: landing or departure
        /// </summary>
        StateType FlightStateType { get; set; }

        /// <summary>
        /// The current station that the flight is on.
        /// </summary>
        Station CurrentStation { get; set; }

        /// <summary>
        /// This method create a thread that initiate the flight.
        /// </summary>
        void InitialteFlight();

        /// <summary>
        /// Abourt the thead of the flight.
        /// </summary>
        void StopFlight();
    }

    /// <summary>
    /// Enumeration of flight state types. can be either landing or departure.
    /// </summary>
    [Serializable]
    public enum StateType
    {
        [EnumMember]
        Landing = 0,
        [EnumMember]
        Departure = 1
    }
}
